module tb_mux_4x1;

  reg i0, i1, i2, i3;
  reg s0, s1;
  wire y;

  mux_4x1 uut(
    .i0(i0), .i1(i1),
    .i2(i2), .i3(i3),
    .s0(s0), .s1(s1),
    .y(y)
  );

  initial begin
    $dumpfile("mux_4x1.vcd");
    $dumpvars(0, tb_mux_4x1);

    i0=1; i1=0; i2=1; i3=0;
    s1=0; s0=0; #10;
    s1=0; s0=1; #10;
    s1=1; s0=0; #10;
    s1=1; s0=1; #10;
  end

endmodule
